### ISSUE TITLE
Truncate at Loop Points

### ISSUE THREAD

**Issue by Kurausukun** [Thealexbarney/LibDspAdpcm#35]
I know you're working on stuff, but I just thought I'd put this here (though you may already know it); I'm not sure when this started, but at least when compiling from the latest master right now, the program no longer truncates files at the loop end point. I only noticed this with idsp, so I'm not sure if it happens with other formats as well. I think there used to be an option for this? Or I may have lost my mind, who knows.

EDIT: Wait, now I'm not totally sure. I made another one and manually cut it off at the loop point, but the file sizes are the same, so maybe it just writes the wrong number for total samples?

**Comment by Thealexbarney** [comment]
Can you provide a file and command to reproduce this? It appears to be working properly for me with something like `Dspadpcm -i file.wav -o out.brstm -l 100000-500000`. WAVE to BRSTM, WAVE to IDSP, and BRSTM to BRSTM trim the output file properly for me

**Comment by Kurausukun** [comment]
Well this was before I downloaded the refactored version--I can't reproduce the problem anymore, so either I lost my mind or it was a very short-lived error. You can close this issue, sorry for the false alarm.
